# Compte Rendu des interviews
## L'interview avec monsieur BOECKX
Le 21 mars 2018 à 14 heure, j'ai eu une conversation avec monsieur BOECKX concernant la base de donnée actuelle, et le but de cet interview soit disant, c'est pour bien comprendre comment ça ce passe l'échange d'information, l'identification de chaque utilisateur dans le Fablab. Et dans ce contexte monsieur BOECKX m'a répondu quasiment à toutes mes questions, il m'a expliqué que la base de donnée était sur Excel mais il n'était pas alèse avec cette base ce qui n'est pas le cas avec la base de donnée actuelle car elle facilite la tâche au niveaux de la récupération d'information concernant chaque utilisateur, d'après lui cette base est avantageux car les données qui sont sur cette base contient les mêmes informations que la fiche d'initiation contient. De plus M. BOECKX est lui qui s'occupe de l'écriture sur cette base ce qui m'a poussé a savoir s'il y a un transfert des données a l'intérieur entre les responsables du Fablab, oui, mais pas a travers la base de donnée actuelle c'est par des fichiers Excel mais pour contrôler les paiements comment va-t-être le contrôle? ce qui m'a lancer a savoir plus sur ce contrôle.
## L'interview avec madame DIRKSEN
Le 22 mars 2018 à 9 heure, j'ai interroger madame DIRKSEN concernant le contrôle de paiement mais malheureusement qu'elle reçoit pas ça d'une manière elle fait la vérification des paiement d'une façon traditionnelle ça veut dire on vérifiant le carnet du fonctionnement car elle s'intervient pas sur la base de donnée actuelle, elle utilise plutôt des fichiers Excel pour établir les échanges de données concernant le paiement avec monsieur DEMARBAIX qui est un formateur dans le Fablab. En effet madame DIRKSEN parfois elle arrive pas a savoir qui a payer et qui reste encore puisque les étudiant parfois font des pièces qui prend pas vraiment de temps et le règlement de paiement pour eux c'est dans trois mois, a chaque trois il doivent payer la somme globale concernant l'utilisation, et ceci m'a donné l'idée d'interroger quelques étudiants pour savoir plus sur la situation actuelle.
## L'interview avec les étudiants
Cet interview c'était plutôt normal il m'a permit de savoir plus sur la situation actuelle pour le contrôle de présence, par exemple les étudiants "groupe robotique" ils m'ont dit qu'il sont pas obligé de signer la fiche de présence a chaque fois, ce qui cause une problématique en cas de problème à l'intérieur du Fablab, j'ai remarqué aussi durant les discussion sur le contrôle du présence que la plupart des étudiants il se sent pas obligé de signer la feuille de présence puisqu'il ont signé la fiche de fonctionnement qui n'est pas autonome non plus, puisque le temps d'utilisation et toujours au dessus du temps indiqué sur la fiche de fonctionnement.

## L'interview avec monsieur FILIPPI
Le 3 avril 2018, j'ai eu un interview avec monsieur FILIPPI en tant que responsable d'achat du matérielle dans le Fablab. L'interview il était basé sur l'état actuelle concernant la présence au sein du Fablab et il m'avait dit que le système ne répond pas vraiment aux besoins, on peut pas savoir et identifier surtout qui est présent dans le Fablab en temps réel. De plus il m'a ramené des fichiers qui porte des solutions déjà établi pour le contrôle d'accès, et de ce départ il a commencé a développé des solutions et comment il voit l'avenir dans le Fablab et cette solution est basée sur un module NFC ou RFID qui identifie chaque utilisateur dans le Fablab en utilisant son badge fournit par le Fablab, il m'a parlé même d'un système qui contrôle la présence pas dans le Fablab seulement mais sur qu'elle machine l'utilisateur travail .
## L'interview avec monsieur DEMARBAIX
Le 17 avril 2018 à 8heur trente, j'ai eu un interview avec monsieur DEMARBAIX en tant que formateur et responsable de la réception des paiements liquides dans le Fablab. L'interview il était basé sur l'état actuelle concernant la présence au sein du Fablab et il m'avait dit qu'il y a toujours des problèmes de identifications des personnes qui sont dans le Fablab, il m'a dit qu'il aime bien savoir qui est dans le Fablab de l'identifie est ce qu'il est parmi les membres, les utilisateurs formés ou parmi les visiteurs. Pour la solution y'avait pas grand chose qui concerne la présence des utilisateurs dans le Fablab, mais on a parler de l'avenir pour la procédure de paiement dans le Fablab qui c'était basé sur un système qui utilise les Bitcoins pour faciliter le paiement pour les utilisateurs mais on a pas resté longtemps sur ce sujet. 
## L'interview avec monsieur ROLAND
Le 17 avril 2018 à 11h, j'ai eu un interview avec monsieur ROLAND en tant que informaticien et chercheur dans le Fablab. L'interview il était basé sur l'état actuelle et l'état futur concernant la présence au sein du Fablab et il m'avait dit pour ce qui concerne l'état actuelle qu'on a pas un protection des données personnelles comme nom, prénom et surtout signature donc c'était la cause pour parler de quelques solutions en ce basant sur l'objectif qui est le contrôle de présence dans le Fablab en mettant en sécurité les donnée personnelle et pour mettre en palace cette solution il m'a parlé des données personnelles nécessaire pour le moment, afin de réaliser un premier test et avec cette solution l'identification sera plus rapide et y'avait comme proposition de base de données pour l'appel d'information M.ROLAND m'a proposé le CLOUD structure où on va utiliser tout ce qui est gratuit car avec google cloud y'a plusieurs menu professionnel mais ils sont paiement, c'est pour ça on c'était mis d'accord sur les menus gratuits comme "App Engine" pour le design et "Datastore" pour stocker les informations. On a parler aussi de la récupération des données existant déjà sur la base de donnée actuelle qui a pour avantage le gain du temps en plus on évite le décodage de 220 ligne de donnée sur la nouvelle base de donnée.
Dans la dernière point on a parlé de la sécurité des données avec une sorte de cryptage "clé publique" et "clé privé"  et la documentation pour donné l'accès a celui qui va prendre le relève pour améliorer ou modifier le système. C'était un interview professionnelle... 
